/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Thread: typeof import('./src/components/thread.vue')['default']
    Thread_detail: typeof import('./src/components/thread_detail.vue')['default']
    Thread_list: typeof import('./src/components/thread_list.vue')['default']
  }
}
